apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  selector:
   matchLabels:
    app: pgadmin
  replicas: 1
  # start of pod specs config file
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:

        - name: pgadmin4
          image: dpage/pgadmin4
          # not set up for secrets right now
          env:
           - name: PGADMIN_DEFAULT_EMAIL
             valueFrom: 
              secretKeyRef:
                name: pgadmin-secret
                key: pgadmin-root-username
           - name: PGADMIN_DEFAULT_PASSWORD
             valueFrom:
              secretKeyRef:
                name: pgadmin-secret
                key: pgadmin-root-password
           - name: PGADMIN_PORT
             value: "80"
          ports:
            - containerPort: 80
              name: pgadminport
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  labels:
    app: pgadmin
spec:
  selector:
   app: pgadmin
  ports:
   - port: 80 # service port 
     targetPort: 80 # container port
     protocol: TCP