# allows the service to run with a set of permissions giving ingress
# controller the ability to do what it needs to do.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-ingress-serviceaccount
  namespace: ingress-nginx